### PR TITLE
support functions with `this` parameters

### LINKED ISSUE #7: [expect-type] `this` param ignored in `.toEqualTypeOf`
Repro:

```ts
import { expectTypeOf } from 'expect-type'

type NoThisParam = (a: number) => void
type DateThisParam = (this: Date, a: number) => void
type UndefinedThisParam = (this: undefined, a: number) => void
type UnknownThisParam = (this: unknown, a: number) => void
type AnyThisParam = (this: any, a: number) => void

// `NoThisParam` and `UnknownThisParam` are the only ones that should be considered equivalent.

expectTypeOf<NoThisParam>().toEqualTypeOf<NoThisParam>();
expectTypeOf<NoThisParam>().not.toEqualTypeOf<DateThisParam>(); // Fails!
expectTypeOf<NoThisParam>().not.toEqualTypeOf<UndefinedThisParam>(); // Fails!
expectTypeOf<NoThisParam>().toEqualTypeOf<UnknownThisParam>();
expectTypeOf<NoThisParam>().not.toEqualTypeOf<AnyThisParam>(); // Fails!
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkaG2AtDAcnQFCdsZwByEHAAtgAZwAKAQyhTaAXjgAKKQC44AOwCuIAEbIoASjjyAfHABuEYABMe7OABEpMZCPHTZC5TFFj1zq4ANHBqmjr6RibmVrb2fACqGjbIxMAayDbukjJyJj5+6lrJqemZIWHaegbGZpbWdrzIcEkA1hoQAO4a2Z55ikq+4kUa7V0aFepVkbUxDfHNAIIaeL253oOFoSuT4dVRdbF2nAD0J3AABoJrXhfbNpdtHd03cncyzb7NEBoANnhwH7IMRwXwuOBiYQQLS-B76OCYH5iWwGTIoACOWmAFikv2QGhgADpuIwsLh2CQADzXPx9ECmJSGQkwCAAUUxuPwRGI1KEtPWDMMAG5OKTsFzkFSaR4BYzCR0iSz2VpORSeYE3PyvIKhXAznAAGJSYC-MQAQlF6DJEqlfJl2rlCuZbI5vxtPKSKTSGSyWrkOr15yNJvNlqY5O5vNe9LlStd7spT3G0Z1YetaqjfpjTKdcZVbozy1WWYD+uDpotQA)

### PR DESCRIPTION
**Pull request by mmkal**
Fixes #7

Porting over https://github.com/mmkal/ts/pull/252 - thank you @papb for creating that one.

### CODE REVIEW

**Comment by papb** [comment]
Great, thank you for picking it up, sorry I didn't have the time to finish it.

**Comment by papb** [comment]
What about [this comment](https://github.com/mmkal/ts/pull/252/files#r820321069), though? I see you didn't add as many tests.

**Comment by mmkal** [comment]
> What about [this comment](https://github.com/mmkal/ts/pull/252/files#r820321069), though? I see you didn't add as many tests.

I stand by my original comment, most of the assertions seemed duplicative of ones that already existed once. Having said that, I renamed `test/index.test.ts` to `test/usage.test.ts` to more strongly hint that the "main" test file is used as a hybrid test-the-core-features and document-core-feature-use-cases tests. So, I would happily accept a PR creating a new test file that has extra tests that don't affect the readme though. I think the competing concerns of readme succinctness and clarity vs individual test self-containment were the reason for us disagreeing on how many there should be, so separating into separate files should solve that problem.

**Comment by papb** [comment]
Cool! Can you add a note to the contributing section about creating test files not named `usage`? As I understand, anything not named `usage.test.ts` will still run as a test but won't fill the readme, is this right?

**Pull request merged**
